window.CITY_ORDER = ['Chicago','St. Louis','Tulsa','Lawton','Austin'];

window.CITY_META = {
  'Chicago': { map:{x:80,y:18}, note:'Chicago ist als eine Stadt zusammengefasst – keine Aufteilung nach Reisetagen.', scores:{nightlife:9.2,safety:7.8,tourist:9.0,lateFood:9.4} },
  'St. Louis': { map:{x:61,y:42}, note:'Kompakte Auswahl, am besten per Rideshare planen.', scores:{nightlife:7.4,safety:7.0,tourist:7.6,lateFood:7.8} },
  'Tulsa': { map:{x:43,y:60}, note:'Tulsa bewusst reduziert. Der falsche Jaguar-Autohaus-Treffer wird blockiert.', scores:{nightlife:7.1,safety:7.5,tourist:7.2,lateFood:7.0} },
  'Lawton': { map:{x:38,y:78}, note:'Kleine lokale Auswahl plus Casino-/Bar-Alternative.', scores:{nightlife:5.7,safety:7.2,tourist:6.2,lateFood:5.9} },
  'Austin': { map:{x:28,y:92}, note:'Austin ist als eine Stadt zusammengefasst und erweitert.', scores:{nightlife:9.5,safety:8.1,tourist:9.2,lateFood:9.1} }
};

window.ADULT_PLACES = [
  {name:"Rick's Cabaret Chicago",localImage:'img-city-premium',city:'Chicago',category:'Tabledance',priority:'Pflichtmarker',rating:4.5,vibe:'Zentral, Premium-Vibe, starke Hauptoption.',address:'1531 N Kingsbury St, Chicago, IL 60642',query:"Rick's Cabaret Chicago 1531 N Kingsbury St Chicago",website:'https://www.rickschicago.com/',map:{x:78.7,y:16.3},accent:'#ff4fd8',imageLabel:'Official / Exterior',imageQuery:"Rick's Cabaret Chicago exterior official photos"},
  {name:'Polekatz Chicago',localImage:'img-neon-club',city:'Chicago',category:'Tabledance',priority:'Top Rated',rating:4.6,vibe:'Großer Club und starke Alternative.',address:'Chicago, IL',query:'Polekatz Chicago adult nightclub',website:'https://www.google.com/search?q=Polekatz+Chicago',map:{x:81.7,y:17.2},accent:'#b56cff',imageLabel:'Google Maps Exterior',imageQuery:'Polekatz Chicago exterior photos'},
  {name:'The Baton Show Lounge',localImage:'img-stage-show',city:'Chicago',category:'Cabaret / Drag Show',priority:'Special',rating:4.7,vibe:'Show-Alternative statt klassischem Stripclub.',address:'Chicago, IL',query:'The Baton Show Lounge Chicago',website:'https://thebatonshowlounge.com/',map:{x:80.5,y:20.1},accent:'#46d6e6',imageLabel:'Official / Social',imageQuery:'The Baton Show Lounge Chicago official photos'},
  {name:'Deja Vu Showgirls Chicago',localImage:'img-red-stage',city:'Chicago',category:'Tabledance',priority:'Top Rated',rating:4.2,vibe:'Bekannte, mainstreamige Option.',address:'Chicago, IL',query:'Deja Vu Showgirls Chicago adult nightclub',website:'https://www.google.com/search?q=Deja+Vu+Showgirls+Chicago',map:{x:77.5,y:18.7},accent:'#ff5f7e',imageLabel:'Exterior Search',imageQuery:'Deja Vu Showgirls Chicago exterior photos'},
  {name:'The Gold Room Chicago',localImage:'img-gold-lounge',city:'Chicago',category:'Gentlemen’s Club',priority:'Top Rated',rating:4.4,vibe:'Gute Zusatzoption für einen späteren Abend.',address:'Chicago, IL',query:"The Gold Room Chicago Gentlemen's Club",website:'https://www.google.com/search?q=The+Gold+Room+Chicago+Gentlemen%27s+Club',map:{x:82.6,y:19.5},accent:'#ffc857',imageLabel:'Exterior Search',imageQuery:"The Gold Room Chicago Gentlemen's Club exterior photos"},
  {name:'Admiral Theatre Chicago',localImage:'img-theatre',city:'Chicago',category:'Adult Entertainment',priority:'Special',rating:4.1,vibe:'Bekannte Chicago-Adresse, vorher Website/Google prüfen.',address:'Chicago, IL',query:'Admiral Theatre Chicago adult entertainment',website:'https://www.google.com/search?q=Admiral+Theatre+Chicago',map:{x:79.3,y:21.4},accent:'#7cf58a',imageLabel:'Exterior Search',imageQuery:'Admiral Theatre Chicago exterior photos'},

  {name:"Scarlett's Cabaret St. Louis",localImage:'img-red-cabaret',city:'St. Louis',category:'Tabledance',priority:'Pflichtmarker',rating:4.3,vibe:'Hauptpick für St. Louis.',address:'St. Louis / East St. Louis area',query:"Scarlett's Cabaret St. Louis",website:'https://www.google.com/search?q=Scarlett%27s+Cabaret+St.+Louis',map:{x:59.7,y:40.7},accent:'#ff4fd8',imageLabel:'Exterior Search',imageQuery:"Scarlett's Cabaret St. Louis exterior photos"},
  {name:'Country Rock Cabaret',localImage:'img-country-stage',city:'St. Louis',category:'Tabledance',priority:'Top Rated',rating:4.1,vibe:'Lokalerer Vibe und gute zweite Option.',address:'St. Louis area',query:'Country Rock Cabaret St. Louis',website:'https://www.google.com/search?q=Country+Rock+Cabaret+St.+Louis',map:{x:62.4,y:43.4},accent:'#ffc857',imageLabel:'Exterior Search',imageQuery:'Country Rock Cabaret St. Louis exterior photos'},

  {name:'Night Trips Tulsa',localImage:'img-blue-stage',city:'Tulsa',category:'Tabledance',priority:'Pflichtmarker',rating:4.2,vibe:'Bekannteste Tulsa-Empfehlung.',address:'3902 S Sheridan Rd, Tulsa, OK 74145',query:'Night Trips Tulsa 3902 S Sheridan Rd Tulsa OK',website:'https://nighttrips.com/Tulsa/',map:{x:41.8,y:58.8},accent:'#ff4fd8',imageLabel:'Official / Website',imageQuery:'Night Trips Tulsa exterior official photos'},
  {name:"Lady Godiva's Tulsa",localImage:'img-purple-neon',city:'Tulsa',category:'Adult Nightlife',priority:'Top Rated',rating:4.1,vibe:'Lokale Option, nicht als Hauptziel pushen.',address:'Tulsa, OK',query:"Lady Godiva's Tulsa adult nightlife",website:'https://www.google.com/search?q=Lady+Godiva%27s+Tulsa',map:{x:44.4,y:61.6},accent:'#b56cff',imageLabel:'Exterior Search',imageQuery:"Lady Godiva's Tulsa exterior photos"},

  {name:'Dragon West',localImage:'img-roadside-night',city:'Lawton',category:'Gentlemen’s Club',priority:'Pflichtmarker',rating:4.0,vibe:'Lokaler Nightlife-Pick für Lawton.',address:'Lawton, OK',query:'Dragon West Lawton OK gentlemen club',website:'https://www.google.com/search?q=Dragon+West+Lawton+OK',map:{x:36.8,y:77.1},accent:'#ffc857',imageLabel:'Exterior Search',imageQuery:'Dragon West Lawton OK exterior photos'},
  {name:'Apache Casino Bar Area',localImage:'img-casino',city:'Lawton',category:'Casino / Bar',priority:'Special',rating:4.2,vibe:'Saubere Bar-/Casino-Alternative.',address:'Apache Casino Hotel, Lawton, OK',query:'Apache Casino Hotel Lawton',website:'https://www.apachecasinohotel.com/',map:{x:39.4,y:79.2},accent:'#7cf58a',imageLabel:'Official / Website',imageQuery:'Apache Casino Hotel Lawton official photos'},

  {name:'Yellow Rose Austin',localImage:'img-yellow-rose',city:'Austin',category:'Tabledance',priority:'Pflichtmarker',rating:4.6,vibe:'Austin-Klassiker und stärkster Premium-Hauptpick.',address:'6528 N Lamar Blvd, Austin, TX 78752',query:'Yellow Rose Austin 6528 N Lamar Blvd',website:'https://www.yellowrose.com/',map:{x:26.3,y:90.6},accent:'#ff4fd8',imageLabel:'Official / Website',imageQuery:'Yellow Rose Austin exterior official photos'},
  {name:'Palazio Austin',localImage:'img-luxury-club',city:'Austin',category:'Tabledance',priority:'Pflichtmarker',rating:4.5,vibe:'Premium Cabaret und zweiter Pflichtmarker in Austin.',address:'Austin, TX',query:'Palazio Austin',website:'https://palaziomensclub.com/',map:{x:28.5,y:90.9},accent:'#b56cff',imageLabel:'Official / Website',imageQuery:'Palazio Austin exterior official photos'},
  {name:'XTC Cabaret Austin',localImage:'img-xtc',city:'Austin',category:'Tabledance',priority:'Top Rated',rating:4.2,vibe:'Großer Club, gut für späten Abend.',address:'Austin, TX',query:'XTC Cabaret Austin',website:'https://www.google.com/search?q=XTC+Cabaret+Austin',map:{x:25.9,y:93.0},accent:'#ff5f7e',imageLabel:'Exterior Search',imageQuery:'XTC Cabaret Austin exterior photos'},
  {name:"Michelle's Beach House",localImage:'img-steakhouse',city:'Austin',category:'Steakhouse / Gentlemen’s Club',priority:'Top Rated',rating:4.3,vibe:'Steakhouse-/Club-Konzept, besonderer Zusatzpick.',address:'Austin, TX',query:"Michelle's Beach House Austin",website:'https://www.google.com/search?q=Michelle%27s+Beach+House+Austin',map:{x:30.0,y:91.7},accent:'#ffc857',imageLabel:'Exterior Search',imageQuery:"Michelle's Beach House Austin exterior photos"},
  {name:'Chicas Bonitas Austin',localImage:'img-latin-neon',city:'Austin',category:'Adult Nightlife',priority:'Top Rated',rating:4.0,vibe:'Alternative mit rauerem Vibe, nicht als Hauptziel.',address:'Austin, TX',query:'Chicas Bonitas Austin',website:'https://www.google.com/search?q=Chicas+Bonitas+Austin',map:{x:28.8,y:94.0},accent:'#46d6e6',imageLabel:'Google Maps Exterior',imageQuery:'Chicas Bonitas Austin exterior photos'},
  {name:'Perfect 10 Austin',localImage:'img-perfect10',city:'Austin',category:'Gentlemen’s Club',priority:'Special',rating:4.1,vibe:'Zusätzliche Austin-Option, vorher prüfen.',address:'Austin, TX',query:'Perfect 10 Austin gentlemen club',website:'https://www.google.com/search?q=Perfect+10+Austin+gentlemen+club',map:{x:31.2,y:92.7},accent:'#7cf58a',imageLabel:'Exterior Search',imageQuery:'Perfect 10 Austin gentlemen club exterior photos'}
];
