window.ADULT_DAYS = [
  { id:'2026-05-14', label:'14.05', title:'Chicago Ankunft', city:'Chicago', note:'Nach Ankunft nur optional. Wenn überhaupt: zentral und ohne langen Rückweg.', picks:['Rick\'s Cabaret Chicago','VIP\'s Gentlemen\'s Club'] },
  { id:'2026-05-15', label:'15.05', title:'Chicago Stadttag', city:'Chicago', note:'Bester Abend für Chicago. Empfehlung: 1 Hauptlocation statt Club-Hopping.', picks:['Rick\'s Cabaret Chicago','Admiral Theatre','VIP\'s Gentlemen\'s Club'] },
  { id:'2026-05-16', label:'16.05', title:'Chicago → St. Louis', city:'Chicago', note:'Fahrtag. Nur sehr spät/locker in Chicago oder lieber überspringen.', picks:['Rick\'s Cabaret Chicago'] },
  { id:'2026-05-17', label:'17.05', title:'St. Louis Stadttag', city:'St. Louis', note:'Die großen Clubs liegen überwiegend auf der Illinois-Seite bei East St. Louis / Centreville / Sauget. Taxi/Rideshare fest einplanen.', picks:['Diamond Cabaret St. Louis','Larry Flynt\'s Hustler Club St. Louis','Club Onyx St. Louis'] },
  { id:'2026-05-18', label:'18.05', title:'St. Louis → Tulsa', city:'St. Louis', note:'Lange Etappe nach Tulsa. Adult-Nightlife an diesem Tag eher nicht empfehlen.', picks:['Diamond Cabaret St. Louis'] },
  { id:'2026-05-19', label:'19.05', title:'Tulsa', city:'Tulsa', note:'Tulsa-Auswahl bewusst kurz halten. Night Trips ist die sichere Hauptempfehlung.', picks:['Night Trips Tulsa','Sensations Gentlemen\'s Club'] },
  { id:'2026-05-20', label:'20.05', title:'Wichita', city:'Wichita', note:'Ich habe Wichita als Wichita, Kansas interpretiert. Falls Wichita Falls gemeint ist, tausche die Daten gegen Maximus / Bombshells.', picks:['Michelle\'s Beach House','Executive Lounge Wichita','Lizzy\'s Gentlemen\'s Club'] },
  { id:'2026-05-21', label:'21.05', title:'Austin Ankunft', city:'Austin', note:'Nach langer Fahrt: Yellow Rose ist die stärkste unkomplizierte Wahl; alternativ Rick\'s North Austin, falls ihr nördlich unterwegs seid.', picks:['Yellow Rose Cabaret','Rick\'s Cabaret North Austin'] },
  { id:'2026-05-22', label:'22.05', title:'Austin Finale', city:'Austin', note:'Datum von 22.05.2027 auf 22.05.2026 korrigiert, passend zur Reiseroute. Austin hat die beste Auswahl; 1–2 Locations reichen.', picks:['Yellow Rose Cabaret','Palazio Men\'s Club','Rick\'s Cabaret North Austin'] }
];

window.ADULT_PLACES = [
  { name:"Rick's Cabaret Chicago", city:'Chicago', category:'Tabledance / Gentlemen\'s Club', priority:'Top', vibe:'Zentral, Full-Liquor, klassische Premium-Option in Chicago.', address:'1531 N Kingsbury St, Chicago, IL 60642', query:"Rick's Cabaret Chicago 1531 N Kingsbury St Chicago", website:'https://www.rickschicago.com/' },
  { name:'Admiral Theatre', city:'Chicago', category:'Nudebar / Fully Nude / BYOB', priority:'Wichtig', vibe:'Historische, große Chicago-Institution; eher bewusst als Spezialfall planen.', address:'3940 W Lawrence Ave, Chicago, IL 60625', query:'Admiral Theatre 3940 W Lawrence Ave Chicago', website:'https://lnk.bio/admiralx' },
  { name:"VIP's Gentlemen's Club", city:'Chicago', category:'Topless Cabaret', priority:'Solide Alternative', vibe:'Zentraler als viele Alternativen, full-liquor/topless Format.', address:'1531 N Kingsbury St, Chicago, IL 60642', query:"VIP's Gentlemen's Club Chicago 1531 N Kingsbury St", website:'http://www.vipschicago.com' },

  { name:'Diamond Cabaret St. Louis', city:'St. Louis', category:'Tabledance / Gentlemen\'s Club', priority:'Top', vibe:'Nächste große Option zu Downtown St. Louis, mit Full Bar, VIP und Küche.', address:'1401 Mississippi Ave, East St. Louis, IL 62201', query:'Diamond Cabaret St. Louis East St Louis', website:'https://www.diamondcabaretstlouis.com/' },
  { name:"Larry Flynt's Hustler Club St. Louis", city:'St. Louis', category:'Tabledance / Gentlemen\'s Club', priority:'Wichtig', vibe:'Bekannte Marke, große Club-Struktur, gut als Alternative zu Diamond.', address:'5420 Bunkum Rd, Washington Park, IL 62204', query:"Larry Flynt's Hustler Club St. Louis", website:'https://stlouishustlerclub.com/' },
  { name:'Club Onyx St. Louis', city:'St. Louis', category:'Urban Gentlemen\'s Club', priority:'Alternative', vibe:'Urban/Hip-Hop-orientiert; vorher aktuelle Öffnung und Lage prüfen.', address:'247 88th St, Centreville, IL 62207', query:'Club Onyx St Louis 247 88th St Centreville', website:'https://www.clubonyxstl.com/' },

  { name:'Night Trips Tulsa', city:'Tulsa', category:'Tabledance / Gentlemen\'s Club', priority:'Top', vibe:'Die naheliegendste und bekannteste Tulsa-Empfehlung; Full-Liquor, VIP, Küche.', address:'3902 S Sheridan Rd, Tulsa, OK 74145', query:'Night Trips Tulsa 3902 S Sheridan Rd', website:'https://nighttrips.com/Tulsa/' },
  { name:"Sensations Gentlemen's Club", city:'Tulsa', category:'Nudebar / All Nude', priority:'Spezialfall', vibe:'Außerhalb Richtung Inola; nur wählen, wenn ihr bewusst eine All-Nude/BYOB-Option wollt.', address:'9373 S 4250 Rd, Inola, OK 74036', query:"Sensations Gentlemen's Club Inola OK", website:'https://sensationsgc.club/' },

  { name:"Michelle's Beach House", city:'Wichita', category:'Tabledance / Gentlemen\'s Club', priority:'Top', vibe:'Etablierte Wichita/Derby-Option, seit Jahren bekannte lokale Adresse.', address:'239 W Greenway St, Derby, KS 67037', query:"Michelle's Beach House Derby Kansas", website:'https://michellesbeachhouse.com/' },
  { name:'Executive Lounge Wichita', city:'Wichita', category:'Gentlemen\'s Club', priority:'Wichtig', vibe:'Wichita-Alternative mit mehreren Locations/Areas laut Website.', address:'Wichita, KS', query:'Executive Lounge Wichita gentlemen club', website:'https://www.executiveloungewichita.com/' },
  { name:"Lizzy's Gentlemen's Club", city:'Wichita', category:'Gentlemen\'s Club', priority:'Alternative', vibe:'Klassische lokale Option; 21+ laut eigener Seite.', address:'Wichita, KS', query:"Lizzy's Gentlemen's Club Wichita Kansas", website:'https://lizzysclub.com/' },

  { name:'Yellow Rose Cabaret', city:'Austin', category:'Tabledance / Gentlemen\'s Club', priority:'Top', vibe:'Austin-Klassiker: stark für Essen, Bottle Service und unkomplizierten Hauptabend.', address:'6528 N Lamar Blvd, Austin, TX 78752', query:'Yellow Rose Cabaret Austin 6528 N Lamar Blvd', website:'https://www.yellowrose.com/' },
  { name:"Palazio Men's Club", city:'Austin', category:'Tabledance / Gentlemen\'s Club', priority:'Wichtig', vibe:'Gute South-Austin-Option, wenn ihr südlich vom Zentrum unterwegs seid.', address:'501 E Ben White Blvd, Austin, TX 78704', query:"Palazio Men's Club Austin 501 E Ben White Blvd", website:'https://palaziomensclub.com/' },
  { name:"Rick's Cabaret North Austin", city:'Austin', category:'Tabledance / Gentlemen\'s Club', priority:'Alternative', vibe:'Nördlich der Stadt, passend bei Rückweg/Hotel/Interstate-Lage.', address:'3105 S I-35 Frontage Rd, Round Rock/Austin area', query:"Rick's Cabaret North Austin", website:'https://www.ricksnorthaustin.com/' }
];
