
const PLACES=window.ADULT_PLACES||[], CITY_META=window.CITY_META||{}, CITY_ORDER=window.CITY_ORDER||[...new Set(PLACES.map(p=>p.city))];
let activeCity='all', activePlace=null, onlineState=navigator.onLine, deferredInstallPrompt=null;
const $=id=>document.getElementById(id); const slug=s=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const maps=q=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
const imgSearch=p=>`https://www.google.com/search?tbm=isch&q=${encodeURIComponent(p.imageQuery||p.name+' exterior official photos')}`;
const web=p=>p.website||`https://www.google.com/search?q=${encodeURIComponent(p.name+' '+p.city)}`;
function cls(c=''){c=c.toLowerCase(); if(c.includes('casino'))return'cat-casino'; if(c.includes('cabaret')||c.includes('drag'))return'cat-show'; if(c.includes('gentlemen'))return'cat-gentlemen'; if(c.includes('adult'))return'cat-adult'; return'cat-table'}
function art(p){return `<div class="photo-art" style="--accent:${p.accent||'#ff4fd8'}"><div class="neon-frame"></div><div class="stage-lines"></div><div class="club-name">${p.name}</div><div class="art-caption">${p.imageLabel||'Location-Bild'}</div></div>`}
function status(t){const e=$('status'); if(e)e.textContent=t}
function scores(m){let s=m.scores||{};return `<div class="score-row"><div class="score"><b>Nightlife</b><span>${s.nightlife||'-'}</span></div><div class="score"><b>Safety</b><span>${s.safety||'-'}</span></div><div class="score"><b>Tourist</b><span>${s.tourist||'-'}</span></div><div class="score"><b>Late Food</b><span>${s.lateFood||'-'}</span></div></div>`}
function card(p,i){return `<article class="place" id="${slug(p.name)}"><button class="photo" onclick="selectPlace(${i})">${art(p)}<span class="tier">${p.priority}</span><span class="image-label">${p.imageLabel}</span></button><div class="body"><h3>${p.name}</h3><div class="badges"><span class="badge gold">⭐ ${p.rating}</span><span class="badge pink">${p.category}</span></div><div class="meta">${p.vibe}<br>${p.address}</div><div class="actions"><a href="${web(p)}" target="_blank">Website / Suche</a><a class="secondary" href="${maps(p.query)}" target="_blank">Google Maps</a><a class="secondary" href="${imgSearch(p)}" target="_blank">Bilder</a><button onclick="selectPlace(${i})">Auf Karte</button></div></div></article>`}
function renderCities(){const r=$('cities'); if(!r)return; r.innerHTML=CITY_ORDER.map(c=>{let ps=PLACES.filter(p=>p.city===c),m=CITY_META[c]||{};return `<section class="glass city-section" id="${slug(c)}"><div class="city-top"><div class="city-title"><div class="eyebrow">${ps.length} Locations · online live / offline gespeichert</div><h2>${c}</h2><p class="vibe">${m.note||''}</p></div>${scores(m)}</div><div class="place-grid">${ps.map(p=>card(p,PLACES.indexOf(p))).join('')}</div></section>`}).join('')}
function cityPin(c){let p=CITY_META[c].map,a=activeCity===c?' active':'';return `<button class="city-pin${a}" style="left:${p.x}%;top:${p.y}%" onclick="focusCity('${c.replace(/'/g,"\\'")}')"><span>${c}</span><small>${PLACES.filter(p=>p.city===c).length} Orte</small></button>`}
function marker(p,i){let a=activePlace===i?' active':'';return `<button class="place-pin ${cls(p.category)}${a}" style="left:${p.map.x}%;top:${p.map.y}%;--accent:${p.accent}" onclick="selectPlace(${i})"><span class="pin-core"></span><span class="place-label">${p.name}<small>${p.city}</small></span></button>`}
function popup(){if(activePlace===null)return'';let p=PLACES[activePlace];return `<aside class="map-popup"><button class="popup-close" onclick="clearPlace()">×</button><div class="popup-photo">${art(p)}</div><div class="popup-body"><div class="eyebrow">${p.city} · ${p.category}</div><h3>${p.name}</h3><p>${p.address}</p><div class="actions"><a href="${maps(p.query)}" target="_blank">Google Maps</a><a class="secondary" href="${web(p)}" target="_blank">Website</a><a class="secondary" href="${imgSearch(p)}" target="_blank">Bilder</a></div></div></aside>`}
function renderMap(){let e=$('map'); if(!e)return; let pts=CITY_ORDER.map(c=>CITY_META[c].map), line=pts.map(p=>`${p.x},${p.y}`).join(' '), shown=activeCity==='all'?PLACES:PLACES.filter(p=>p.city===activeCity); e.innerHTML=`<svg class="route-svg" viewBox="0 0 100 100" preserveAspectRatio="none"><defs><linearGradient id="routeGrad"><stop offset="0" stop-color="#ff4fd8"/><stop offset="1" stop-color="#46d6e6"/></linearGradient></defs><polyline points="${line}" fill="none" stroke="url(#routeGrad)" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"/></svg><div class="city-layer">${CITY_ORDER.map(cityPin).join('')}</div><div class="place-layer">${shown.map(p=>marker(p,PLACES.indexOf(p))).join('')}</div><div class="legend"><span><i class="cat-table"></i>Tabledance</span><span><i class="cat-gentlemen"></i>Gentlemen</span><span><i class="cat-show"></i>Show</span><span><i class="cat-casino"></i>Casino</span></div>${popup()}`; status(`${onlineState?'Online':'Offline'}-Modus: ${shown.length} Location-Marker auf der Karte.`)}
function focusCity(c){activeCity=c;activePlace=null;renderMap();document.getElementById(slug(c))?.scrollIntoView({behavior:'smooth'})} function fitAll(){activeCity='all';activePlace=null;renderMap()} function selectPlace(i){activePlace=i;activeCity=PLACES[i].city;renderMap();$('karte')?.scrollIntoView({behavior:'smooth'})} function clearPlace(){activePlace=null;renderMap()}
function nearMe(){alert(onlineState?'Online-Modus: Maps/Website/Bilder öffnen live.':'Offline-Modus: gespeicherte App bleibt sichtbar.')} function installApp(){let ios=/iphone|ipad|ipod/i.test(navigator.userAgent),stand=matchMedia('(display-mode: standalone)').matches||navigator.standalone; if(stand)return alert('Die App läuft bereits im App-Modus.'); if(deferredInstallPrompt){deferredInstallPrompt.prompt();deferredInstallPrompt.userChoice.finally(()=>deferredInstallPrompt=null);return} alert(ios?'In Safari teilen → Zum Home-Bildschirm.':'Browser-Menü → App installieren / Zum Startbildschirm hinzufügen.')} 
async function checkOnline(){try{await fetch('./manifest.webmanifest?ping='+Date.now(),{cache:'no-store'});onlineState=true}catch(e){onlineState=navigator.onLine} document.body.classList.toggle('is-online',onlineState);document.body.classList.toggle('is-offline',!onlineState);renderMap()}
function init(){renderCities();renderMap();checkOnline(); if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js?v=12').catch(()=>{})}
addEventListener('online',checkOnline);addEventListener('offline',checkOnline);addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;document.body.classList.add('can-install');status('App installierbar.')});addEventListener('appinstalled',()=>{deferredInstallPrompt=null;status('App installiert.')});
Object.assign(window,{nearMe,fitAll,focusCity,selectPlace,clearPlace,installApp});document.addEventListener('DOMContentLoaded',init);
